---
abstract: 'A postmodern object system for Perl 5'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Test::Exception: 0.21
  Test::LongString: 0
  Test::More: 0.62
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moose
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  Class::MOP: 0.64_01
  Filter::Simple: 0
  List::MoreUtils: 0
  Scalar::Util: 1.18
  Sub::Exporter: 0.972
resources:
  license: http://dev.perl.org/licenses/
version: 0.55_01
