--- 
abstract: A complete modern object system for Perl 5
author: Stevan Little <stevan@iinteractive.com>
build_requires: 
  Test::Exception: 0.21
  Test::LongString: 0
  Test::More: 0.62
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Moose
no_index: 
  directory: 
    - inc
    - t
requires: 
  B: 0
  Carp: 0
  Class::MOP: 0.43
  Scalar::Util: 1.18
  Sub::Exporter: 0.972
  Sub::Name: 0.02
tests: t/*.t t/*/*.t
version: 0.28
