---
abstract: 'A postmodern object system for Perl 5'
author:
  - 'Stevan Little <stevan@iinteractive.com>'
build_requires:
  Test::Fatal: 0.001
  Test::More: 0.88
  Test::Requires: 0.05
configure_requires:
  Dist::CheckConflicts: 0.02
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200001, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Moose
no_index:
  directory:
    - benchmarks
  namespace:
    - Moose::Meta::Method::Accessor::Native
  package:
    - Moose::Meta::Method::Accessor::Native
requires:
  Data::OptList: 0
  Devel::GlobalDestruction: 0
  Eval::Closure: 0
  List::MoreUtils: 0.12
  MRO::Compat: 0.05
  Package::DeprecationManager: 0.10
  Package::Stash: 0.16
  Package::Stash::XS: 0.17
  Params::Util: 1.00
  Scalar::Util: 1.19
  Sub::Exporter: 0.980
  Sub::Name: 0.05
  Task::Weaken: 0
  Try::Tiny: 0.02
  perl: 5.8.3
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Moose
  repository: git://git.moose.perl.org/Moose.git
version: 1.9902
x_authority: cpan:STEVAN
x_conflicts:
  Catalyst: 5.80028
  Devel::REPL: 1.003008
  Fey: 0.36
  Fey::ORM: 0.34
  File::ChangeNotify: 0.15
  KiokuDB: 0.49
  Markdent: 0.16
  MooseX::Aliases: 0.07
  MooseX::AlwaysCoerce: 0.05
  MooseX::Attribute::Deflator: 1.130000
  MooseX::Attribute::Dependent: 1.0.0
  MooseX::Attribute::Prototype: 0.10
  MooseX::AttributeHelpers: 0.22
  MooseX::AttributeInflate: 0.02
  MooseX::ClassAttribute: 0.17
  MooseX::FollowPBP: 0.02
  MooseX::HasDefaults: 0.02
  MooseX::InstanceTracking: 0.04
  MooseX::LazyRequire: 0.05
  MooseX::MethodAttributes: 0.22
  MooseX::NonMoose: 0.15
  MooseX::POE: 0.205
  MooseX::Params::Validate: 0.05
  MooseX::Role::Cmd: 0.06
  MooseX::Role::WithOverloading: 0.07
  MooseX::SemiAffordanceAccessor: 0.05
  MooseX::Singleton: 0.24
  MooseX::StrictConstructor: 0.08
  MooseX::Types: 0.19
  MooseX::UndefTolerant: 0.04
  Pod::Elemental: 0.093280
  namespace::autoclean: 0.08
