---
name: Moose
version: 0.01
author:
  - Stevan Little E<lt>stevan@iinteractive.comE<gt>
abstract: "Moose, it's the new Camel"
license: perl
requires:
  Carp: 0
  Class::MOP: 0.21
  Scalar::Util: 1.18
  Sub::Name: 0.02
build_requires:
  Test::Exception: 0.21
  Test::More: 0.47
provides:
  Moose:
    file: lib/Moose.pm
    version: 0.01
  Moose::Meta::Attribute:
    file: lib/Moose/Meta/Attribute.pm
    version: 0.01
  Moose::Meta::Class:
    file: lib/Moose/Meta/Class.pm
    version: 0.01
  Moose::Object:
    file: lib/Moose/Object.pm
    version: 0.01
  Moose::Util::TypeConstraints:
    file: lib/Moose/Util/TypeConstraints.pm
    version: 0.01
generated_by: Module::Build version 0.2611
